### ISSUE TITLE
GitLab API

### ISSUE THREAD

**Issue by OberstVonGatow** [abapGit/abapgit-review-example#18]
Hi Lars,

could you give me a hint how i could use the GitLab Api instead of GitHub?
I have seen you generated it with abap-openapi-client.
I tried to use "possibility to run in browser" but i don't really understand how to use it (unfortunately i'm a Api Noob).
Should i use it in ABAP?

The openapi for GitLab should be https://gitlab.com/gitlab-org/gitlab/blob/master/doc/api/openapi/openapi.yaml
 
Thanks
Fabian

**Comment by larshp** [comment]
the gitlab openapi specification is very partial, so not sure it will work

you can always manually code the api calls
